# Generated by Django 3.0.6 on 2020-11-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=100)),
                ('paid_or_free', models.CharField(max_length=10)),
                ('date_and_time', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['-time_created'],
            },
        ),
    ]
