# Generated by Django 3.0.6 on 2020-11-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('deadline', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
