# Generated by Django 3.0.6 on 2020-11-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201125_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='application_message',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
