# Generated by Django 3.0.6 on 2020-11-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_vacancy_application_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BathSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('one', 'Once'), ('twice', 'Twice'), ('three', 'Three times'), ('vary', 'It varies')], max_length=20)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Bath surveys',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='CauseOfBreakUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'What is the cause of your previous break up',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='CraziestStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Craziest thing ever done for the sake of love surveys',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='FormControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Forms Control',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='HowManyTimesDoYouBrush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'How many times do you brush a day',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='HowMuchDoYouSpendOnCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'How much do you spend on recharge card',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='KindOfPeopleYouLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Which kind of girl or boy do you like?',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='MostConsumedFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Most consumed food on sundays',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'How to desribe a reponsible',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='WhatGivesYouJoyInIphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'What gives you joy in using iphone',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='WhenDisvirgin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'When you were disvirgined',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='WhoProposed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Who proposed surveys',
                'ordering': ['-time'],
            },
        ),
    ]
