# Generated by Django 3.0.6 on 2020-12-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_giveaway_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whendisvirgin',
            options={'ordering': ['-time'], 'verbose_name_plural': 'When you were disvirgin'},
        ),
        migrations.AlterField(
            model_name='bathsurvey',
            name='answer',
            field=models.CharField(choices=[('once', 'Once'), ('two', 'Two times'), ('three', 'Three times'), ('four', 'Four times'), ('varies', 'It varies')], max_length=20),
        ),
    ]
