# Generated by Django 3.0.6 on 2020-11-22 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog images')),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Religion', 'Religion'), ('Gossips', 'Gossips'), ('Health', 'Health'), ('Food', 'Food and Nutrients')], max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog posts',
                'ordering': ['-time'],
            },
        ),
    ]
