# Generated by Django 3.0.6 on 2020-11-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Education', 'Education'), ('Business', 'Business'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Religion', 'Religion'), ('Gossips', 'Gossips'), ('Health', 'Health'), ('Food', 'Food and Nutrients')], max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
