# Generated by Django 3.0.6 on 2020-11-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201125_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Education', 'Education'), ('Business', 'Business'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Religion', 'Religion'), ('Gossips', 'Gossips'), ('Health', 'Health'), ('Food', 'Food and Nutrients'), ('Fitness', 'Fitness'), ('Career', 'Career'), ('result', 'Survey result')], max_length=50),
        ),
    ]
