# Generated by Django 3.0.6 on 2020-12-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201205_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='add_to_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Education', 'Education'), ('Business', 'Business'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Religion', 'Religion'), ('Gossips', 'Gossips'), ('Health', 'Health'), ('Food', 'Food and Nutrients'), ('Fitness', 'Fitness'), ('Career', 'Career'), ('result', 'Survey result'), ('enterpreneur', 'Enterpreneur'), ('job', 'Job')], max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(),
        ),
    ]
